### PR TITLE
fix errors when installing dependencies for AMC

### PR DESCRIPTION
**Pull request by Halytskyi**
Errors when installing dependencies for AMC on Ubuntu Trusty:

1.**pycrypto**

`==> ae: Error: Execution of '/usr/bin/pip install -q pycrypto' returned 1: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wWUhhK-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pycrypto
==> ae: Storing debug log for failure in /root/.pip/pip.log`

Fix: should be installed '_python-dev_ first.

2.**paramiko**

`==> ae: Error: Execution of '/usr/bin/pip install -q paramiko' returned 1: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Dzsamp-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cryptography
==> ae: Storing debug log for failure in /root/.pip/pip.log`

Fix:
- should be installed 'libffi-dev' and 'libssl-dev' first.
- **paramiko** has dependency _cryptography_ which installs another dependency _setuptools_. After that, '_pip freeze_' won’t be work:

```
# pip freeze
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/freeze.py", line 74, in run
    req = pip.FrozenRequirement.from_dist(dist, dependency_links, find_tags=find_tags)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 286, in from_dist
    assert len(specs) == 1 and specs[0][0] == '=='
AssertionError

Storing debug log for failure in /root/.pip/pip.log
```

the reason: for _setuptools_ need more newer version of pip (in Ubuntu Trusty the latest version: _1.5.4_).
To fix this: should be installed one of the latest version of pip. In this case, no reason install pip from Ubuntu repo and then upgrade it. More good way, install the latest version directly from pip repo by '_get-pip.py_' (see https://pip.pypa.io/en/stable/installing/).

Also, as for '_pycrypto_' and '_paramiko_' should be installed part of the dependencies from _$bcrypt_os_packages_, therefore, '_bcrypt_' was added in _$pip_packages_ and _$bcrypt_os_packages_ renamed to _$pip_os_packages_.

### CODE REVIEW

**Comment by pgrandin** [comment]
I have concerns about this:

```
+    exec { 'bootstrap pip':
 +      command => '/usr/bin/curl https://bootstrap.pypa.io/get-pip.py | python',
 +      creates => '/usr/local/bin/pip',
 +    }
```

We should avoid installing files outside of packages. What prevents us from using the pip package from the distro's package manager?

**Comment by Halytskyi** [comment]
This is installation from official source: https://pip.pypa.io/en/stable/installing/
We can install pip package from the distro's package manager and upgrade it by 'pip install -U pip' but in this case we will have two versions of 'pip': one old version 1.5.4 (from Ubuntu repo /usr/bin/pip) and upgraded version in '/usr/local/bin/pip'. But this will work too.
If you consider that this is will better way, I can made necessary changes.

**Comment by aerostitch** [comment]
I'm not a big fan of one or the other solutions, but I guess we don't really have a choice in our case.
I wonder if using the paramiko from the OS package (not from pip) would fix this.
Did you try it?

**Comment by Halytskyi** [comment]
You're right. Paramiko from the OS package solved the problem. I made necessary changes. Result:

> Notice: /Stage[main]/Aerospike::Install/Package[python-pip]/ensure: ensure changed 'purged' to 'present'
> Notice: /Stage[main]/Aerospike::Install/Package[ansible]/ensure: ensure changed 'purged' to 'present'
> Notice: /Stage[main]/Aerospike::Install/Package[python-paramiko]/ensure: ensure changed 'purged' to 'present'
> Notice: /Stage[main]/Aerospike::Install/Package[ecdsa]/ensure: created
> Notice: /Stage[main]/Aerospike::Install/Package[python-dev]/ensure: ensure changed 'purged' to 'present'
> Notice: /Stage[main]/Aerospike::Install/Package[libffi-dev]/ensure: ensure changed 'purged' to 'present'
> Notice: /Stage[main]/Aerospike::Install/Package[bcrypt]/ensure: created
> Notice: /Stage[main]/Aerospike::Install/Archive[/usr/local/src/aerospike-amc-enterprise-3.6.6.all.x86_64.deb]/ensure: download archive from http://www.aerospike.com/artifacts/aerospike-amc-enterprise/3.6.6/aerospike-amc-enterprise-3.6.6.all.x86_64.deb to /usr/local/src/aerospike-amc-enterprise-3.6.6.all.x86_64.deb  without cleanup
> Notice: /Stage[main]/Aerospike::Install/Package[aerospike-amc-enterprise]/ensure: ensure changed 'purged' to 'latest'
> Notice: /Stage[main]/Aerospike::Service/Service[amc]/ensure: ensure changed 'stopped' to 'running'
> Info: /Stage[main]/Aerospike::Service/Service[amc]: Unscheduling refresh on Service[amc]
> Notice: Finished catalog run in 93.34 seconds

Also, I found small other issue. When I try upgrade AMC, new version loaded on server but not installed:

> Notice: /Stage[main]/Aerospike::Install/Archive[/usr/local/src/aerospike-amc-enterprise-3.6.9.all.x86_64.deb]/ensure: download archive from http://www.aerospike.com/artifacts/aerospike-amc-enterprise/3.6.9/aerospike-amc-enterprise-3.6.9.all.x86_64.deb to /usr/local/src/aerospike-amc-enterprise-3.6.9.all.x86_64.deb  without cleanup
> Notice: Finished catalog run in 28.06 seconds

Fixed it by changing "ensure => installed" to "ensure   => latest" for "ensure_packages("aerospike-amc-${aerospike::edition}"".
Result:

> Notice: /Stage[main]/Aerospike::Install/Archive[/usr/local/src/aerospike-amc-enterprise-3.6.9.all.x86_64.deb]/ensure: download archive from http://www.aerospike.com/artifacts/aerospike-amc-enterprise/3.6.9/aerospike-amc-enterprise-3.6.9.all.x86_64.deb to /usr/local/src/aerospike-amc-enterprise-3.6.9.all.x86_64.deb  without cleanup
> Notice: /Stage[main]/Aerospike::Install/Package[aerospike-amc-enterprise]/ensure: ensure changed '3.6.6' to '3.6.9'
> Notice: /Stage[main]/Aerospike::Service/Service[amc]/ensure: ensure changed 'stopped' to 'running'
> Info: /Stage[main]/Aerospike::Service/Service[amc]: Unscheduling refresh on Service[amc]
> Notice: Finished catalog run in 41.15 seconds

**Comment by aerostitch** [comment]
That looks great. Thanks.
Only one point though, can you use `${aerospike::amc_version}` instead of `latest` on the ensure as we want to target a specific version of the amc during the install please.

Thanks! :)

**Comment by aerostitch** [comment]
Sorry didn't notice it was a dpkg provider (so not versionable). Good to go.

**Pull request merged**
